flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.0.2.1
- conduit-extra-1.1.15
- http-client-0.5.4
- http-client-tls-0.3.3
- http-conduit-2.2.3
- mmorph-1.0.9
- req-0.1.0
resolver: lts-7.8
